This project contains a patched version of Writer2LaTeX that should be
able to handle Zotero references in OpenOffice.org Writer documents,
in order to import them into LyX for use with Zotero and LyZ.


* Relevant links:
- [[http://writer2latex.sourceforge.net/][the unpatched Writer2LaTeX]]
- [[http://www.zotero.org/][Zotero]]
- [[http://www.lyx.org/][LyX]]
- [[https://addons.mozilla.org/en-US/firefox/addon/56806/][LyZ (LyX extension for Zotero)]]


* Compilation:

#+BEGIN_SRC
    $ cd trunk
    $ edit build.xml # set OFFICE_CLASSES and URE_CLASSES
    $ ant oxt
#+END_SRC

Also be sure to use [[http://github.com/unhammer/lyz][this patched version of LyZ]], in order to get the
correct bibtex keys from Zotero. Compile it with:

#+BEGIN_SRC
    $ zip -r lyz.xpi ./*
#+END_SRC

You might also want [[http://github.com/unhammer/zotero-natbib][this patched BibTeX translator]] for Zotero, which
adds the "lastchecked" field correctly in order to work with natbib
(and empties the "howpublished" field), also adding ={}= around titles
to capitalise them as in Zotero.

* Usage:

#+BEGIN_SRC
    $ cd trunk/target
    $ java -jar lib/writer2latex.jar -config=classes/writer2latex/latex/config/zotero.xml -latex in.odt out.tex
#+END_SRC

Now import the document as LaTeX from LyX, and change the citekey
format in LyZ to "writer2latex".

* Issues:

LyZ at the moment does not notice references that haven't been used
before in the document, so you'll have to first make one citation of
your whole library (which you can then delete).

There is a small chance of name-collisions if you cite from several
libraries, since we delete the library ID from the bibtex
key. However, I don't use this with more than one library myself, and
don't see a way to include the library ID in the bibtex key unless the
Zotero OOo plugin changes its output format.
